# Generated by Django 6.0.1 on 2026-01-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['tytul']},
        ),
    ]
