# Generated by Django 6.0.1 on 2026-01-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_alter_film_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='kategoria',
            field=models.CharField(choices=[('akcja', 'Akcja'), ('komedia', 'Komedia'), ('dramat', 'Dramat'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('animacja', 'Animacja'), ('dokumentalny', 'Dokumentalny')], max_length=32),
        ),
    ]
