# Generated by Django 6.0.1 on 2026-01-13 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_film_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
