# Generated by Django 6.0.1 on 2026-01-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100, unique=True)),
                ('rok', models.IntegerField()),
                ('opis', models.TextField(blank=True)),
                ('premiera', models.DateField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('plakat', models.ImageField(blank=True, null=True, upload_to='plakaty/')),
            ],
        ),
    ]
