# Generated by Django 6.0.1 on 2026-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=64, unique=True)),
                ('opis', models.TextField(blank=True)),
                ('rok_produkcji', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kategoria', models.CharField(blank=True, max_length=32)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='filmy/')),
            ],
        ),
    ]
